### ISSUE TITLE
PIP Installer not working

### ISSUE THREAD

**Issue by starhopper-de** [Rolf-Hempel/PlanetarySystemStacker#82]
Hello,
I tried to install PSS on my linux observatory PC. It fails completely, please fix it.
Do you need certain logs?
Thomas

```
remote@shuttle:~$ python3 --version
**Python 3.8.10**

remote@shuttle:~$ **pip3 install planetary-system-stacker**
Collecting planetary-system-stacker
  Using cached planetary_system_stacker-0.9.8.2-py3-none-manylinux1_x86_64.whl (232 kB)
Collecting scikit-image
  Downloading scikit_image-0.21.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.9 MB)
     |████████████████████████████████| 13.9 MB 925 kB/s 
Collecting numpy<1.23.0
  Downloading numpy-1.22.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.9 MB)
     |████████████████████████████████| 16.9 MB 299 kB/s 
Collecting astropy
  Downloading astropy-5.2.2-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (11.4 MB)
     |████████████████████████████████| 11.4 MB 1.3 MB/s 
Collecting matplotlib
  Downloading matplotlib-3.7.4-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (9.2 MB)
     |████████████████████████████████| 9.2 MB 716 kB/s 
Requirement already satisfied: psutil in /usr/lib/python3/dist-packages (from planetary-system-stacker) (5.5.1)
Collecting PyQt5>=5.15
  Using cached PyQt5-5.15.10.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /tmp/tmp3mpg_8v7 prepare_metadata_for_build_wheel /tmp/tmpxnpxbs5v
         cwd: /tmp/pip-install-uw4v8ran/PyQt5
    Complete output (32 lines):
    pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
    Traceback (most recent call last):
      File "/tmp/tmp3mpg_8v7", line 126, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/tmp3mpg_8v7", line 280, in <module>
        main()
      File "/tmp/tmp3mpg_8v7", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/tmp/tmp3mpg_8v7", line 130, in prepare_metadata_for_build_wheel
        return _get_wheel_metadata_from_wheel(backend, metadata_directory,
      File "/tmp/tmp3mpg_8v7", line 159, in _get_wheel_metadata_from_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/tmp/pip-build-env-fnnrkj24/overlay/lib/python3.8/site-packages/sipbuild/api.py", line 46, in build_wheel
        project = AbstractProject.bootstrap('wheel',
      File "/tmp/pip-build-env-fnnrkj24/overlay/lib/python3.8/site-packages/sipbuild/abstract_project.py", line 92, in bootstrap
        project.setup(pyproject, tool, tool_description)
      File "/tmp/pip-build-env-fnnrkj24/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 587, in setup
        self.apply_user_defaults(tool)
      File "/tmp/pip-install-uw4v8ran/PyQt5/project.py", line 68, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/tmp/pip-build-env-fnnrkj24/overlay/lib/python3.8/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/tmp/pip-build-env-fnnrkj24/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 237, in apply_user_defaults
        self.builder.apply_user_defaults(tool)
      File "/tmp/pip-build-env-fnnrkj24/overlay/lib/python3.8/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
        raise PyProjectOptionException('qmake',
    sipbuild.pyproject.PyProjectOptionException
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmp3mpg_8v7 prepare_metadata_for_build_wheel /tmp/tmpxnpxbs5v Check the logs for full command output.


```

**Comment by Plutonium5793** [comment]
Pip is no longer working on my Fedora system either.  In my case 
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
is the error message.
According to online comments, this is a python 3.12 issue where they deprecated zipImporter but forgot to tell pip.  So far I haven't found a work around.   I have been trying to install it on windows10 to be able to use it, but the installer for windows 10 is for .83 while the current version is 0.98.   Thus there is no route for me to use 0.98 at this time.

**Comment by starhopper-de** [comment]
I kindly asked for a working way to install PSS.

**Comment by Plutonium5793** [comment]
here is the error message I get from pip:
I particularly enjoy pip absolving itself of any responsibility.

jduchek@HP-K:~$ pip install planetary-system-stacker
Defaulting to user installation because normal site-packages is not writeable
Collecting planetary-system-stacker
  Using cached planetary_system_stacker-0.9.8.2-py3-none-manylinux1_x86_64.whl.metadata (5.2 kB)
Collecting numpy<1.23.0 (from planetary-system-stacker)
  Using cached numpy-1.22.4.zip (11.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/home/jduchek/.local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/jduchek/.local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/jduchek/.local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/home/jduchek/.local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib64/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/tmp/pip-build-env-7z6y4dgj/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/tmp/pip-build-env-7z6y4dgj/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/tmp/pip-build-env-7z6y4dgj/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
jduchek@HP-K:~$

**Comment by Growflavor** [comment]
I see attempts mentioned above were python 3.8 & python 3.12 

RE: python 3.12 so far python 3.10 looks like the most current python for a successful PSS install...

the limit seems to be:
https://github.com/Rolf-Hempel/PlanetarySystemStacker/issues/71
numpy==1.22.4 whl does not want to build on 3.11 and
opencv-python-headless 4.9.0.80 depends on numpy>=1.23.5; python_version >= "3.11"
whereas
opencv-python-headless 4.9.0.80 depends on numpy>=1.21.2; python_version >= "3.10"

Over at the CloudyNights Forum there is also a thread with current discussion for installation parameters & successes & issues with various environments:

https://www.cloudynights.com/topic/753290-planetarysystemstacker-installation-issues/page-2#entry12887153

Ubuntu 22.04 uses Python 3.10.12...see log below where PSS 0.9.8.2 installs OK via pip in a venv (Ubuntu 22.04 running on wsl2 in Windows 10)

I suggest using a dedicated venv for PSS -- for linux based example:

python3 -m venv ./PSSvenv
source ./PSSvenv/bin/activate

pip install -r requirements.txt

using this file:
[requirements.txt](https://github.com/Rolf-Hempel/PlanetarySystemStacker/files/15145917/requirements.txt)

then 

pip install planetary-system-stacker

The above "requirements.txt" which was created from the python 3.10.12 venv via pip freeze > requirements.txt
I have used it to install planetary-system-stacker in a venv created with python 3.10.11 (from the windows store in my 2nd test case)

https://github.com/Rolf-Hempel/PlanetarySystemStacker/issues/66

<details>
  <summary>Here are the packages that were pulled & seem to work (click black arrow to reveal drop down text):</summary>

Ubuntu 22.04 uses Python 3.10.12
PSS 0.9.8.2 seems to install OK via pip in a venv 
Ubuntu 22.04 in wsl2 on Windows 10:

  ```javascript
 growflavor@Alo:~$ python3 --version
Python 3.10.12
growflavor@Alo:~$ python3 -m venv ./PSSvenv
growflavor@Alo:~$ source ./PSSvenv/bin/activate
(PSSvenv) growflavor@Alo:~$ pip install planetary-system-stacker
Collecting planetary-system-stacker
  Downloading planetary_system_stacker-0.9.8.2-py3-none-manylinux1_x86_64.whl (232 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.4/232.4 KB 2.7 MB/s eta 0:00:00
Collecting psutil
  Downloading psutil-5.9.8-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (288 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.2/288.2 KB 4.4 MB/s eta 0:00:00
Collecting astropy
  Downloading astropy-6.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 5.1 MB/s eta 0:00:00
Collecting scipy
  Downloading scipy-1.13.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 4.9 MB/s eta 0:00:00
Collecting matplotlib
  Downloading matplotlib-3.8.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 5.1 MB/s eta 0:00:00
Collecting PyQt5>=5.15
  Downloading PyQt5-5.15.10-cp37-abi3-manylinux_2_17_x86_64.whl (8.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 5.3 MB/s eta 0:00:00
Collecting opencv-python-headless
  Downloading opencv_python_headless-4.9.0.80-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (49.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.6/49.6 MB 2.8 MB/s eta 0:00:00
Collecting numpy<1.23.0
  Downloading numpy-1.22.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 4.2 MB/s eta 0:00:00
Collecting scikit-image
  Downloading scikit_image-0.23.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.7/14.7 MB 5.0 MB/s eta 0:00:00
Collecting PyQt5-sip<13,>=12.13
  Downloading PyQt5_sip-12.13.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.whl (338 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 338.1/338.1 KB 4.2 MB/s eta 0:00:00
Collecting PyQt5-Qt5>=5.15.2
  Downloading PyQt5_Qt5-5.15.2-py3-none-manylinux2014_x86_64.whl (59.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.9/59.9 MB 4.4 MB/s eta 0:00:00
Collecting astropy-iers-data>=0.2024.2.26.0.28.55
  Downloading astropy_iers_data-0.2024.4.29.0.28.48-py3-none-any.whl (1.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 4.5 MB/s eta 0:00:00
Collecting PyYAML>=3.13
  Downloading PyYAML-6.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (705 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 705.5/705.5 KB 3.9 MB/s eta 0:00:00
Collecting pyerfa>=2.0.1.1
  Downloading pyerfa-2.0.1.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (738 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 738.7/738.7 KB 4.6 MB/s eta 0:00:00
Collecting packaging>=19.0
  Downloading packaging-24.0-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.5/53.5 KB 1.2 MB/s eta 0:00:00
Collecting fonttools>=4.22.0
  Downloading fonttools-4.51.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 4.5 MB/s eta 0:00:00
Collecting contourpy>=1.0.1
  Downloading contourpy-1.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (305 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 305.2/305.2 KB 4.4 MB/s eta 0:00:00
Collecting python-dateutil>=2.7
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 KB 4.5 MB/s eta 0:00:00
Collecting pillow>=8
  Downloading pillow-10.3.0-cp310-cp310-manylinux_2_28_x86_64.whl (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 5.2 MB/s eta 0:00:00
Collecting kiwisolver>=1.3.1
  Downloading kiwisolver-1.4.5-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 4.6 MB/s eta 0:00:00
Collecting cycler>=0.10
  Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Collecting pyparsing>=2.3.1
  Downloading pyparsing-3.1.2-py3-none-any.whl (103 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.2/103.2 KB 3.7 MB/s eta 0:00:00
Collecting scikit-image
  Downloading scikit_image-0.23.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.7/14.7 MB 5.4 MB/s eta 0:00:00
  Downloading scikit_image-0.22.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.7/14.7 MB 5.4 MB/s eta 0:00:00
Collecting imageio>=2.27
  Downloading imageio-2.34.1-py3-none-any.whl (313 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 313.5/313.5 KB 4.7 MB/s eta 0:00:00
Collecting networkx>=2.8
  Downloading networkx-3.3-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 5.2 MB/s eta 0:00:00
Collecting lazy_loader>=0.3
  Downloading lazy_loader-0.4-py3-none-any.whl (12 kB)
Collecting tifffile>=2022.8.12
  Downloading tifffile-2024.4.24-py3-none-any.whl (225 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 225.0/225.0 KB 1.8 MB/s eta 0:00:00
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: PyQt5-Qt5, six, PyYAML, PyQt5-sip, pyparsing, psutil, pillow, packaging, numpy, networkx, kiwisolver, fonttools, cycler, astropy-iers-data, tifffile, scipy, python-dateutil, PyQt5, pyerfa, opencv-python-headless, lazy_loader, imageio, contourpy, scikit-image, matplotlib, astropy, planetary-system-stacker
Successfully installed PyQt5-5.15.10 PyQt5-Qt5-5.15.2 PyQt5-sip-12.13.0 PyYAML-6.0.1 astropy-6.0.1 astropy-iers-data-0.2024.4.29.0.28.48 contourpy-1.2.1 cycler-0.12.1 fonttools-4.51.0 imageio-2.34.1 kiwisolver-1.4.5lazy_loader-0.4 matplotlib-3.8.4 networkx-3.3 numpy-1.22.4 opencv-python-headless-4.9.0.80 packaging-24.0 pillow-10.3.0 planetary-system-stacker-0.9.8.2 psutil-5.9.8 pyerfa-2.0.1.4 pyparsing-3.1.2 python-dateutil-2.9.0.post0 scikit-image-0.22.0 scipy-1.13.0 six-1.16.0 tifffile-2024.4.24
(PSSvenv) growflavor@Alo:~$ PlanetarySystemStacker
  ```
  
</details>

**Comment by Growflavor** [comment]
> I have been trying to install it on windows10 to be able to use it, but the installer for windows 10 is for .83 while the current version is 0.98.

@Plutonium5793 
Fortunately for Windows 10 & Windows 11, 0.9.8 currently pulls successfully in python 3.10 from the windows store & the process is quick & quite easy to do...

Overview: In Windows 10 & 11, we can pull any/all major versions (from 3.7 to 3.12) of Python directly from the "Windows Store" app. Then, with one simple cmd line, we can create a venv for any specific Python version we have installed from the store in ANY folder we make/choose, as follows:

1) On Windows 10 or 11, from the "Windows Store" app search for 'python' & install python 3.10 (currently installs 3.10.11)

2) create a folder for PSS anywhere you want...In my case I chose to simply create & name the new folder PSS on my 'faster' workspace SSD X:

3) (see image below as example): Enter the folder you created from Windows Explorer & place your mouse cursor over any 'white space' in that folder and hold down the SHIFT key while you click the right mouse button...from the menu that opens select 'Open Command Prompt' (or PowerShell or Terminal) to open a terminal in that folder...Command Prompt is easiest...so if only PowerShell is an option then open that and then once you are in PowerShell type cmd to get the Windows Command Prompt. 

note: you can name the python venv whatever you want, I just chose 'pssvenv' to be descriptive in my case...

In either command prompt or PowerShell (PS) enter the following commands shown in bold text :

PS X:\Workspace\PSS> **python3.10 -m venv pssvenv**

--> ignore the next step if you are already in Windows Command prompt rather than PowerShell:
PS X:\Workspace\PSS> **cmd**

X:\zFASTworkspace\PSS> **pssvenv\scripts\activate**
(pssvenv) X:\zFASTworkspace\PSS> **pssvenv\Scripts\python.exe -m pip install --upgrade pip**
(pssvenv) X:\zFASTworkspace\PSS> **pip install planetary-system-stacker**

![Win10CreatePYvenv2](https://github.com/Rolf-Hempel/PlanetarySystemStacker/assets/1580559/d04f90c1-1aba-4186-bf7e-b7ec102a779c)

<details>
  <summary>Windows 10 or 11 creating Python 3.10 venv & installing PlanetarySystemStacker from PowerShell/cmd (click black arrow to show the drop down with example install log text)</summary>
 

If you are already in windows command prompt, ignore the line that executes 'cmd'

  ```javascript
PS X:\zFASTworkspace\PSS> python3.10 -m venv pssvenv		
		
PS X:\zFASTworkspace\PSS> cmd		
Microsoft Windows [Version 10.0.19045.4291]		
(c) Microsoft Corporation. All rights reserved.		
				
X:\zFASTworkspace\PSS>pssvenv\scripts\activate		

(pssvenv) X:\zFASTworkspace\PSS>pssvenv\Scripts\python.exe -m pip install --upgrade pip
Requirement already satisfied: pip in x:\zfastworkspace\pss\pssvenv\lib\site-packages (23.0.1)		
Collecting pip		
Using cached pip-24.0-py3-none-any.whl (2.1 MB)		
Installing collected packages: pip		
Attempting uninstall: pip		
Found existing installation: pip 23.0.1		
Uninstalling pip-23.0.1:		
Successfully uninstalled pip-23.0.1		
Successfully installed pip-24.0		

(pssvenv) X:\zFASTworkspace\PSS>pip3 install planetary-system-stacker		

Collecting planetary-system-stacker		
Downloading planetary_system_stacker-0.9.8.1-py3-none-win_amd64.whl.metadata (5.2 kB)		
Requirement already satisfied: numpy<1.23.0 in x:\zfastworkspace\pss\pssvenv\lib\site-packages (from planetary-system-stacker) (1.22.4)		
Requirement already satisfied: matplotlib in x:\zfastworkspace\pss\pssvenv\lib\site-packages (from planetary-system-stacker) (3.8.4)		
Requirement already satisfied: psutil in x:\zfastworkspace\pss\pssvenv\lib\site-packages (from planetary-system-stacker) (5.9.8)		
Requirement already satisfied: PyQt5 in x:\zfastworkspace\pss\pssvenv\lib\site-packages (from planetary-system-stacker) (5.15.10)		
Requirement already satisfied: scipy in x:\zfastworkspace\pss\pssvenv\lib\site-packages (from planetary-system-stacker) (1.13.0)		
Requirement already satisfied: astropy in x:\zfastworkspace\pss\pssvenv\lib\site-packages (from planetary-system-stacker) (6.0.1)		
Requirement already satisfied: scikit-image in x:\zfastworkspace\pss\pssvenv\lib\site-packages (from planetary-system-stacker) (0.22.0)		
Collecting opencv-python (from planetary-system-stacker)		
Downloading opencv_python-4.9.0.80-cp37-abi3-win_amd64.whl.metadata (20 kB)		
Requirement already satisfied: pyerfa>=2.0.1.1 in x:\zfastworkspace\pss\pssvenv\lib\site-packages (from astropy->planetary-system-stacker) (2.0.1.4)		
Requirement already satisfied: astropy-iers-data>=0.2024.2.26.0.28.55 in x:\zfastworkspace\pss\pssvenv\lib\site-packages (from astropy->planetary-system-stacker) (0.2024.4.29.0.28.48)		
Requirement already satisfied: PyYAML>=3.13 in x:\zfastworkspace\pss\pssvenv\lib\site-packages (from astropy->planetary-system-stacker) (6.0.1)		
Requirement already satisfied: packaging>=19.0 in x:\zfastworkspace\pss\pssvenv\lib\site-packages (from astropy->planetary-system-stacker) (24.0)		
Requirement already satisfied: contourpy>=1.0.1 in x:\zfastworkspace\pss\pssvenv\lib\site-packages (from matplotlib->planetary-system-stacker) (1.2.1)		
Requirement already satisfied: cycler>=0.10 in x:\zfastworkspace\pss\pssvenv\lib\site-packages (from matplotlib->planetary-system-stacker) (0.12.1)		
Requirement already satisfied: fonttools>=4.22.0 in x:\zfastworkspace\pss\pssvenv\lib\site-packages (from matplotlib->planetary-system-stacker) (4.51.0)		
Requirement already satisfied: kiwisolver>=1.3.1 in x:\zfastworkspace\pss\pssvenv\lib\site-packages (from matplotlib->planetary-system-stacker) (1.4.5)		
Requirement already satisfied: pillow>=8 in x:\zfastworkspace\pss\pssvenv\lib\site-packages (from matplotlib->planetary-system-stacker) (10.3.0)		
Requirement already satisfied: pyparsing>=2.3.1 in x:\zfastworkspace\pss\pssvenv\lib\site-packages (from matplotlib->planetary-system-stacker) (3.1.2)		
Requirement already satisfied: python-dateutil>=2.7 in x:\zfastworkspace\pss\pssvenv\lib\site-packages (from matplotlib->planetary-system-stacker) (2.9.0.post0)		
Requirement already satisfied: PyQt5-sip<13,>=12.13 in x:\zfastworkspace\pss\pssvenv\lib\site-packages (from PyQt5->planetary-system-stacker) (12.13.0)		
Requirement already satisfied: PyQt5-Qt5>=5.15.2 in x:\zfastworkspace\pss\pssvenv\lib\site-packages (from PyQt5->planetary-system-stacker) (5.15.2)		
Requirement already satisfied: networkx>=2.8 in x:\zfastworkspace\pss\pssvenv\lib\site-packages (from scikit-image->planetary-system-stacker) (3.3)		
Requirement already satisfied: imageio>=2.27 in x:\zfastworkspace\pss\pssvenv\lib\site-packages (from scikit-image->planetary-system-stacker) (2.34.1)		
Requirement already satisfied: tifffile>=2022.8.12 in x:\zfastworkspace\pss\pssvenv\lib\site-packages (from scikit-image->planetary-system-stacker) (2024.4.24)		
Requirement already satisfied: lazy_loader>=0.3 in x:\zfastworkspace\pss\pssvenv\lib\site-packages (from scikit-image->planetary-system-stacker) (0.4)		
Requirement already satisfied: six>=1.5 in x:\zfastworkspace\pss\pssvenv\lib\site-packages (from python-dateutil>=2.7->matplotlib->planetary-system-stacker) (1.16.0)		
Downloading planetary_system_stacker-0.9.8.1-py3-none-win_amd64.whl (232 kB)		
---------------------------------------- 232.4/232.4 kB 712.1 kB/s eta 0:00:00		
Downloading opencv_python-4.9.0.80-cp37-abi3-win_amd64.whl (38.6 MB)		
---------------------------------------- 38.6/38.6 MB 3.4 MB/s eta 0:00:00		
Installing collected packages: opencv-python, planetary-system-stacker		
Successfully installed opencv-python-4.9.0.80 planetary-system-stacker-0.9.8.1		
		
(pssvenv) X:\zFASTworkspace\PSS>PlanetarySystemStacker		
  ```  
</details>

To run PSS:
(pssvenv) X:\zFASTworkspace\PSS> **PlanetarySystemStacker**

To exit the venv:
(pssvenv) X:\zFASTworkspace\PSS> **deactivate**

To exit cmd:
X:\zFASTworkspace\PSS> **exit**

To exit Poweshell:
PS X:\Workspace\PSS> **exit**

To launch PSS in the future, repeat SHIFT-right click to open a cmd terminal in your PSS folder, then

X:\zFASTworkspace\PSS> **pssvenv\scripts\activate**
(pssvenv) X:\zFASTworkspace\PSS> **PlanetarySystemStacker**

For anyone new to working with Python on any platform, venv are very important for reducing headaches from python 'package conflicts'...here is one useful reference/discussion/tutorial to read regarding the 'best practice why' & 'how' to use python venv virtual environments:

https://www.dataquest.io/blog/a-complete-guide-to-python-virtual-environments/

**Comment by Theladik** [comment]
Hi, 

I am getting the following error when running PIP installer.

ERROR: Could not find a version that satisfies the requirement planetary-system-stacker (from versions: none)
ERROR: No matching distribution found for planetary-system-stacker

Mac OS 14.6.1

Any ideas?

Thanks
